/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Admin.admindashboard;
import User.userdashboard;
import config.config;
import javax.swing.JOptionPane;
import config.Session;
import java.awt.Color;
import javax.swing.JPanel;
/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 167, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 359, -1));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Username: ");
        jLabel4.setToolTipText("");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        jPanel5.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password: ");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel5.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 310, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Forgot Password?");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 20));

        Login.setBackground(new java.awt.Color(96, 165, 250));
        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
        });
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Log In");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 30));

        jPanel5.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 240, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Not Registered Yet?");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        registerbtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        registerbtn.setForeground(new java.awt.Color(51, 255, 51));
        registerbtn.setText("Register Now!");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });
        jPanel5.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New logo.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 90));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Log In");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

                public void setColor(JPanel p){
        p.setBackground(new Color(96,165,250));
    }
    
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(0,102,153));
    }
    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
          Register registerbtn = new Register ();
          registerbtn.setVisible(true);
          dispose();// TODO add your handling code here:
    }//GEN-LAST:event_registerbtnMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
       
        String email = Email.getText();
    String password = Pass.getText();

    if (email.equals("") || password.equals("")) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        return;
    }

    String sql = "SELECT * FROM tbl_accounts WHERE email = ? AND password = ?";
    boolean success = false;
    String userType = "";

    // STEP 1: Check credentials and set Session
    try (
        java.sql.Connection conn = config.connectDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ) {
        pst.setString(1, email);
        pst.setString(2, password);

        try (java.sql.ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                if (!rs.getString("status").equalsIgnoreCase("Active")) {
                    JOptionPane.showMessageDialog(null, "Account inactive. Contact Admin.");
                    return;
                }

                // Populate Session while rs is open
                Session.setSession(
                    rs.getInt("a_id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("type")
                );

                userType = rs.getString("type");
                success = true;
            } else {
                JOptionPane.showMessageDialog(null, "Invalid email or password!");
                return;
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Login Error: " + e.getMessage());
        return;
    }

    // STEP 2: Record Log (Now OUTSIDE the connection block to prevent Database Lock)
    if (success) {
        config conf = new config();
        String logSql = "INSERT INTO tbl_logs (a_id, log_event) VALUES (?, ?)";
        conf.addRecord(logSql, Session.getUserId(), "Logged In");

        JOptionPane.showMessageDialog(null, "LOGIN SUCCESS!");

        // STEP 3: Navigation
        if (userType.equalsIgnoreCase("Admin")) {
            new admindashboard().setVisible(true);
        } else if (userType.equalsIgnoreCase("User")) {
            new userdashboard().setVisible(true);
        } else if (userType.equalsIgnoreCase("Rider")) { 
            new User.riderdashboard().setVisible(true); 
        }
        this.dispose();
    
    }//GEN-LAST:event_LoginMouseClicked
        }
    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        resetColor(Login);        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        setColor(Login);        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JPanel Login;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel registerbtn;
    // End of variables declaration//GEN-END:variables
}
