/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Main.Landingpage;
import Main.Login;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    public admindashboard() {
        
        if (config.Session.getUserId() == 0) 
        {
        JOptionPane.showMessageDialog(null, "Login Required!");
        new Login().setVisible(true);
        dispose();
        return;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Users = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Home1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Logs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Transactions = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Rider = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Assignment = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 420, 70));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 140));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Users.setBackground(new java.awt.Color(0, 102, 153));
        Users.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsersMouseExited(evt);
            }
        });
        Users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("USERS");
        Users.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 20));

        jPanel2.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 60));

        Home1.setBackground(new java.awt.Color(0, 102, 153));
        Home1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home1MouseExited(evt);
            }
        });
        Home1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("PROFILE");
        Home1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, 20));

        jPanel2.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 270, 60));

        Logs.setBackground(new java.awt.Color(0, 102, 153));
        Logs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogsMouseExited(evt);
            }
        });
        Logs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("LOGS");
        Logs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 60, 20));

        jPanel2.add(Logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 60));

        Transactions.setBackground(new java.awt.Color(0, 102, 153));
        Transactions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Transactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransactionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionsMouseExited(evt);
            }
        });
        Transactions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TRANSACTIONS");
        Transactions.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel2.add(Transactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 270, 70));

        Rider.setBackground(new java.awt.Color(0, 102, 153));
        Rider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RiderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RiderMouseExited(evt);
            }
        });
        Rider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("RIDER TRANSACTIONS");
        Rider.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.add(Rider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 70));

        Assignment.setBackground(new java.awt.Color(0, 102, 153));
        Assignment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Assignment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssignmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssignmentMouseExited(evt);
            }
        });
        Assignment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ASSIGNMENT");
        Assignment.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        jPanel2.add(Assignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 340, 470));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (2).png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buildings.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 90, 820, 390));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 590, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
        public void setColor(JPanel p){
        p.setBackground(new Color(0,102,153));
    }
    
    public void resetColor(JPanel p2){
        p2.setBackground(new Color(96,165,250));
    }
    
    private void TransactionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMouseEntered
        resetColor(Transactions);
    }//GEN-LAST:event_TransactionsMouseEntered

    private void TransactionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMouseExited
        setColor(Transactions);
    }//GEN-LAST:event_TransactionsMouseExited

    private void UsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseEntered
        resetColor(Users);
    }//GEN-LAST:event_UsersMouseEntered

    private void UsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseExited
        setColor(Users);
    }//GEN-LAST:event_UsersMouseExited

    private void UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersMouseClicked
        users Users = new users();
        Users.setVisible(true);
        dispose();
    }//GEN-LAST:event_UsersMouseClicked

    private void Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseClicked
        profile Home1 =  new profile ();
        Home1.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Home1MouseClicked

    private void Home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseEntered
        resetColor(Home1);        // TODO add your handling code here:
    }//GEN-LAST:event_Home1MouseEntered

    private void Home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseExited
        setColor(Home1);        // TODO add your handling code here:
    }//GEN-LAST:event_Home1MouseExited

    private void TransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMouseClicked
        records Transactions = new records();
        Transactions.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionsMouseClicked

    private void LogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseClicked
    logs LogsFrame = new logs(); // Ensure the class name in logs.java is 'logs'
    LogsFrame.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LogsMouseClicked

    private void LogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseEntered
       resetColor(Logs); // TODO add your handling code here:
    }//GEN-LAST:event_LogsMouseEntered

    private void LogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogsMouseExited
        setColor(Logs);// TODO add your handling code here:
    }//GEN-LAST:event_LogsMouseExited

    private void AssignmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentMouseClicked
                
        Assignment Send = new Assignment();
        Send.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentMouseClicked

    private void AssignmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentMouseEntered
        resetColor(Assignment);            // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentMouseEntered

    private void AssignmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignmentMouseExited
        setColor(Assignment);   // TODO add your handling code here:
    }//GEN-LAST:event_AssignmentMouseExited

    private void RiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiderMouseClicked

        ridertransactions Rider = new ridertransactions();
        Rider.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_RiderMouseClicked

    private void RiderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiderMouseEntered
        resetColor(Rider);        // TODO add your handling code here:
    }//GEN-LAST:event_RiderMouseEntered

    private void RiderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiderMouseExited
        setColor(Rider);        // TODO add your handling code here:
    }//GEN-LAST:event_RiderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Assignment;
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel Logs;
    private javax.swing.JPanel Rider;
    private javax.swing.JPanel Transactions;
    private javax.swing.JPanel Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
